import random
from typing import Tuple, Optional
from torch.utils.data import DataLoader
from transformers import AutoProcessor
from dataset import StanfordCarsDataset
from utils import parse_stanford_mat_files

def create_dataloaders(train_dir: str, test_dir: Optional[str] = None, llm_captions_path: str = "llm_captions.json", processor_name: str = "google/siglip-base-patch16-224", 
                       batch_size: int = 32, num_workers: int = 8, val_split: float = 0.1) -> Tuple[DataLoader, DataLoader, Optional[DataLoader], object]:
    """Creates PyTorch DataLoaders for the Stanford Cars dataset, integrating LLM-generated captions.
    Args:        
        train_dir: Path to the training data directory containing images and annotations
        test_dir: Path to the test data directory (Optional. If None, test_loader is None)
        llm_captions_path: Path to the JSON file generated by the offline LLM script
        processor_name: Name or path to the pre-trained processor
        batch_size: Number of samples per batch
        num_workers: Number of subprocesses to use for data loading
        val_split: Percentage of the training set to reserve for validation
    Returns:        
        train_loader: DataLoader for the training set
        val_loader: DataLoader for the validation set
        test_loader: DataLoader for the test set (None if test_dir is None)
        processor: The processor for handling both image and text inputs
    """

    print("Loading the input Processor...")
    # Load the processor to handle both the ViT image resizing and the text tokenization
    processor = AutoProcessor.from_pretrained(processor_name)

    # Get training and validation records
    print("Building Data Records...")
    all_train_records, _ = parse_stanford_mat_files(train_dir, split="train")
    
    # Fixed seed to ensure consistent splits across DDP processes
    random.seed(42)
    random.shuffle(all_train_records)
    val_size = int(len(all_train_records) * val_split)
    
    val_records = all_train_records[:val_size]
    train_records = all_train_records[val_size:]

    print(f"Found {len(train_records)} training images and {len(val_records)} validation images.")

    # Instantiate training and validation dataset classes
    train_dataset = StanfordCarsDataset(
        data_records=train_records,
        processor=processor,
        llm_captions_path=llm_captions_path,
        split="train"
    )
    
    val_dataset = StanfordCarsDataset(
        data_records=val_records,
        processor=processor,
        llm_captions_path=llm_captions_path,
        split="test"
    )

    # Create training and validation DataLoaders
    train_loader = DataLoader(
        train_dataset,
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers,
        pin_memory=True,
        drop_last=True
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=True,
        drop_last=False
    )

    # Create test DataLoader if test_dir is provided, otherwise set to None
    test_loader = None
    if test_dir is not None:
        test_records, _ = parse_stanford_mat_files(test_dir, split="test")
        print(f"Found {len(test_records)} test images.")
        
        test_dataset = StanfordCarsDataset(
            data_records=test_records,
            processor=processor,
            llm_captions_path=llm_captions_path,
            split="test"
        )
        
        test_loader = DataLoader(
            test_dataset,
            batch_size=batch_size,
            shuffle=False,
            num_workers=num_workers,
            pin_memory=True,
            drop_last=False
        )

    return train_loader, val_loader, test_loader, processor

if __name__ == "__main__":
    # Create dataloaders and processor
    train_loader, val_loader, test_loader, processor = create_dataloaders(
        train_dir="./data/stanford_cars",
        test_dir="./data/stanford_cars",
        llm_captions_path="./data/llm_captions.json",
        processor_name="google/siglip-base-patch16-224",
        batch_size=64,
        num_workers=8,
        val_split=0.1
    )
    
    # Sanity check
    batch = next(iter(train_loader))
    print("\nSanity Check - Batch Shapes:")
    print(f"Pixel Values (Images): {batch['pixel_values'].shape}") 
    # Expected: [64, 3, 224, 224]
    print(f"Input IDs (Text): {batch['input_ids'].shape}")       
    # Expected: [64, 64]
    print(f"Sample Raw Text: {batch['raw_text'][0]}")